# ================================================
# AUTO-GENERATED FILE
# Do NOT edit manually.
# Generated from label_mapping_completed.csv
# ================================================

LABEL_MAPPING = {

    ("Apple_Disease_Dataset", "Apple___Apple_scab"): "Apple_Scab",
    ("Apple_Disease_Dataset", "Apple___Black_rot"): "Apple_Black_Rot",
    ("Apple_Disease_Dataset", "Apple___Cedar_apple_rust"): "Apple_Cedar_Apple_Rust",
    ("Apple_Disease_Dataset", "Apple___healthy"): "Apple_Healthy",
    ("Cassava", "cbb"): "Cassava_Bacterial_Blight",
    ("Cassava", "cbsd"): "Cassava_Brown_Streak_Disease",
    ("Cassava", "cgm"): "Cassava_Green_Mite",
    ("Cassava", "cmd"): "Cassava_Mosaic_Disease",
    ("Cassava", "healthy"): "Cassava_Healthy",
    ("PlantVillage", "Apple___Apple_scab"): "Apple_Scab",
    ("PlantVillage", "Apple___Black_rot"): "Apple_Black_Rot",
    ("PlantVillage", "Apple___Cedar_apple_rust"): "Apple_Cedar_Apple_Rust",
    ("PlantVillage", "Apple___healthy"): "Apple_Healthy",
    ("PlantVillage", "Blueberry___healthy"): "Blueberry_healthy",
    ("PlantVillage", "Cherry_(including_sour)___Powdery_mildew"): "Cherry_(including_sour)_Powdery_mildew",
    ("PlantVillage", "Cherry_(including_sour)___healthy"): "Cherry_(including_sour)_healthy",
    ("PlantVillage", "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot"): "Corn_(maize)_Cercospora_leaf_spot_Gray_leaf_spot",
    ("PlantVillage", "Corn_(maize)___Common_rust_"): "Corn_(maize)_Common_rust_",
    ("PlantVillage", "Corn_(maize)___Northern_Leaf_Blight"): "Corn_(maize)_Northern_Leaf_Blight",
    ("PlantVillage", "Corn_(maize)___healthy"): "Corn_(maize)_healthy",
    ("PlantVillage", "Grape___Black_rot"): "Grape_Black_rot",
    ("PlantVillage", "Grape___Esca_(Black_Measles)"): "Grape_Esca_(Black_Measles)",
    ("PlantVillage", "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)"): "Grape_Leaf_blight_(Isariopsis_Leaf_Spot)",
    ("PlantVillage", "Grape___healthy"): "Grape_healthy",
    ("PlantVillage", "Orange___Haunglongbing_(Citrus_greening)"): "Orange_Haunglongbing_(Citrus_greening)",
    ("PlantVillage", "Peach___Bacterial_spot"): "Peach_Bacterial_spot",
    ("PlantVillage", "Peach___healthy"): "Peach_healthy",
    ("PlantVillage", "Pepper,_bell___Bacterial_spot"): "Bell_Pepper_Bacterial_Spot",
    ("PlantVillage", "Pepper,_bell___healthy"): "Bell_Pepper_Healthy",
    ("PlantVillage", "Potato___Early_blight"): "Potato_Early_Blight",
    ("PlantVillage", "Potato___Late_blight"): "Potato_Late_Blight",
    ("PlantVillage", "Potato___healthy"): "Potato_Healthy",
    ("PlantVillage", "Raspberry___healthy"): "Raspberry_healthy",
    ("PlantVillage", "Soybean___healthy"): "Soybean_healthy",
    ("PlantVillage", "Squash___Powdery_mildew"): "Squash_Powdery_mildew",
    ("PlantVillage", "Strawberry___Leaf_scorch"): "Strawberry_Leaf_scorch",
    ("PlantVillage", "Strawberry___healthy"): "Strawberry_healthy",
    ("PlantVillage", "Tomato___Bacterial_spot"): "Tomato_Bacterial_Spot",
    ("PlantVillage", "Tomato___Early_blight"): "Tomato_Early_Blight",
    ("PlantVillage", "Tomato___Late_blight"): "Tomato_Late_Blight",
    ("PlantVillage", "Tomato___Leaf_Mold"): "Tomato_Leaf_Mold",
    ("PlantVillage", "Tomato___Septoria_leaf_spot"): "Tomato_Septoria_Leaf_Spot",
    ("PlantVillage", "Tomato___Spider_mites Two-spotted_spider_mite"): "Tomato_Spider_Mites",
    ("PlantVillage", "Tomato___Target_Spot"): "Tomato_Target_Spot",
    ("PlantVillage", "Tomato___Tomato_Yellow_Leaf_Curl_Virus"): "Tomato_Yellow_Leaf_Curl_Virus",
    ("PlantVillage", "Tomato___Tomato_mosaic_virus"): "Tomato_Mosaic_Virus",
    ("PlantVillage", "Tomato___healthy"): "Tomato_Healthy",
    ("plantDoc", "Apple_Scab_Leaf"): "Apple_Scab",
    ("plantDoc", "Apple_leaf"): "Apple_Healthy",
    ("plantDoc", "Apple_rust_leaf"): "Apple_Black_Rot",
    ("plantDoc", "Bell_pepper_leaf"): "Bell_Pepper_Healthy",
    ("plantDoc", "Bell_pepper_leaf_spot"): "Bell_Pepper_Bacterial_Spot",
    ("plantDoc", "Blueberry_leaf"): "Blueberry_leaf",
    ("plantDoc", "Cherry_leaf"): "Cherry_leaf",
    ("plantDoc", "Corn_Gray_leaf_spot"): "Corn_Gray_leaf_spot",
    ("plantDoc", "Corn_leaf_blight"): "Corn_leaf_blight",
    ("plantDoc", "Corn_rust_leaf"): "Corn_rust_leaf",
    ("plantDoc", "Peach_leaf"): "Peach_leaf",
    ("plantDoc", "Potato_leaf_early_blight"): "Potato_Early_Blight",
    ("plantDoc", "Potato_leaf_late_blight"): "Potato_Late_Blight",
    ("plantDoc", "Raspberry_leaf"): "Raspberry_leaf",
    ("plantDoc", "Soyabean_leaf"): "Soyabean_leaf",
    ("plantDoc", "Squash_Powdery_mildew_leaf"): "Squash_Powdery_mildew_leaf",
    ("plantDoc", "Strawberry_leaf"): "Strawberry_leaf",
    ("plantDoc", "Tomato_Early_blight_leaf"): "Tomato_Early_Blight",
    ("plantDoc", "Tomato_Septoria_leaf_spot"): "Tomato_Septoria_Leaf_Spot",
    ("plantDoc", "Tomato_leaf"): "Tomato_Healthy",
    ("plantDoc", "Tomato_leaf_bacterial_spot"): "Tomato_Bacterial_Spot",
    ("plantDoc", "Tomato_leaf_late_blight"): "Tomato_Late_Blight",
    ("plantDoc", "Tomato_leaf_mosaic_virus"): "Tomato_Mosaic_Virus",
    ("plantDoc", "Tomato_leaf_yellow_virus"): "Tomato_Yellow_Leaf_Curl_Virus",
    ("plantDoc", "Tomato_mold_leaf"): "Tomato_Leaf_Mold",
    ("plantDoc", "Tomato_two_spotted_spider_mites_leaf"): "Tomato_Spider_Mites",
    ("plantDoc", "grape_leaf"): "grape_leaf",
    ("plantDoc", "grape_leaf_black_rot"): "grape_leaf_black_rot",
    ("rice-leaf-disease-riceguard", "blast"): "Rice_Blast",
    ("rice-leaf-disease-riceguard", "healthy"): "Rice_Healthy",
    ("rice-leaf-disease-riceguard", "insect"): "Rice_Insect_Damage",
    ("rice-leaf-disease-riceguard", "leaf_folder"): "Rice_Leaf_Folder",
    ("rice-leaf-disease-riceguard", "scald"): "Rice_Scald",
    ("rice-leaf-disease-riceguard", "stripes"): "Rice_Bacterial_Leaf_Stripe",
    ("rice-leaf-disease-riceguard", "tungro"): "Rice_Tungro",
}
